# $ docker-compose up --build
# $ docker-compose up
# version: '3'
services:
  db:
    image: mysql:8
    container_name: animelist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: animelist

    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - animelist-net

  app:
    build: .
    container_name: animelist-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/animelist
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - animelist-net

volumes:
  db-data:

networks:
  animelist-net: