#spring.datasource.url=jdbc:mysql://localhost:3306/gtalent1
spring.datasource.url=jdbc:mysql://db:3306/gtalent1
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.sql.init.mode=always
