#docker-compose up --build
services:
  db:
    image: mysql:8
    restart: always
    container_name: gtalent-jdbc-mysql-db
    environment:
      MYSQL_DATABASE: gtalent1
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name:  gtalent-springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gtalent1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: