# docker-compose up --build
version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: gtalent1
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    image: my-springboot-app:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
