# docker-compose up
# docker-compose up --build
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: life-insurance-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: life_insurance
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: life-insurance-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-net
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://db:3306/life_insurance
      SPRING_R2DBC_USERNAME: appuser
      SPRING_R2DBC_PASSWORD: apppassword
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: classpath:schema.sql

volumes:
  mysql-data:

networks:
  app-net:
